### ISSUE TITLE
Kwalitee can't be run after fresh installation

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/kwalitee#70]
After successful pip installation in local virtualenv:
```
$ kwalitee
Traceback (most recent call last):
  File "/usr/local/bin/kwalitee", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/kwalitee/cli/__init__.py", line 43, in main
    manager.app = create_app()
  File "/usr/local/lib/python2.7/dist-packages/kwalitee/factory.py", line 60, in create_app
    os.makedirs(app.instance_path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/var'
```

**Comment by kaplun** [comment]
Nevermind. Looks like conflict with global installation.
