### ISSUE TITLE
Error on commit

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/kwalitee#89]
With the latest master version from Github and after installing the hooks. I get the following error:

```
Traceback (most recent call last):
  File ".git/hooks/prepare-commit-msg", line 9, in <module>
    load_entry_point('kwalitee', 'console_scripts', 'kwalitee-prepare-commit-msg')()
  File "python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "src/kwalitee/kwalitee/hooks.py", line 148, in prepare_commit_msg_hook
    options.get('template'))
  File "src/kwalitee/kwalitee/hooks.py", line 96, in _prepare_commit_msg
    with open(tmp_file, "r", "utf-8") as fh:
  File "lib/python2.7/codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'commit'
```

**Comment by tiborsimko** [comment]
@jmartinm Works well in CLI mode otherwise? (without hooks)

**Comment by jmartinm** [comment]
Yes.

```bash
$ kwalitee check message
$ kwalitee check files
$ kwalitee check message
```

They all give correct output in CLI.

PS. I actually did not know that you can use it in CLI mode :) Would be nice to mention it in https://github.com/inveniosoftware/kwalitee/blob/master/README.rst

**Comment by jirikuncar** [comment]
FYI https://pythonhosted.org/kwalitee/cli.html

**Comment by jmartinm** [comment]
> FYI https://pythonhosted.org/kwalitee/cli.html

👍

**Comment by tiborsimko** [comment]
(Anyway we should update our CLI docs, now that e.g. `kwalitee accounts` is gone, and `check authors` came... I'll look at it.)
